# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mumble_link_server.models.base_model_ import Model
from mumble_link_server import util


class ServerServerIdUserUserIdBanPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reason=None, duration=None):  # noqa: E501
        """ServerServerIdUserUserIdBanPostRequest - a model defined in OpenAPI

        :param reason: The reason of this ServerServerIdUserUserIdBanPostRequest.  # noqa: E501
        :type reason: str
        :param duration: The duration of this ServerServerIdUserUserIdBanPostRequest.  # noqa: E501
        :type duration: int
        """
        self.openapi_types = {
            'reason': str,
            'duration': int
        }

        self.attribute_map = {
            'reason': 'reason',
            'duration': 'duration'
        }

        self._reason = reason
        self._duration = duration

    @classmethod
    def from_dict(cls, dikt) -> 'ServerServerIdUserUserIdBanPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _server__server_id__user__user_id__ban_post_request of this ServerServerIdUserUserIdBanPostRequest.  # noqa: E501
        :rtype: ServerServerIdUserUserIdBanPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self):
        """Gets the reason of this ServerServerIdUserUserIdBanPostRequest.


        :return: The reason of this ServerServerIdUserUserIdBanPostRequest.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ServerServerIdUserUserIdBanPostRequest.


        :param reason: The reason of this ServerServerIdUserUserIdBanPostRequest.
        :type reason: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason

    @property
    def duration(self):
        """Gets the duration of this ServerServerIdUserUserIdBanPostRequest.


        :return: The duration of this ServerServerIdUserUserIdBanPostRequest.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this ServerServerIdUserUserIdBanPostRequest.


        :param duration: The duration of this ServerServerIdUserUserIdBanPostRequest.
        :type duration: int
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")  # noqa: E501

        self._duration = duration
