# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mumble_link_server.models.base_model_ import Model
from mumble_link_server.models.actions import Actions
from mumble_link_server import util

from mumble_link_server.models.actions import Actions  # noqa: E501

class ServerServerIdGroupGroupIdPutRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, allowed_actions=None, denied_actions=None):  # noqa: E501
        """ServerServerIdGroupGroupIdPutRequest - a model defined in OpenAPI

        :param name: The name of this ServerServerIdGroupGroupIdPutRequest.  # noqa: E501
        :type name: str
        :param allowed_actions: The allowed_actions of this ServerServerIdGroupGroupIdPutRequest.  # noqa: E501
        :type allowed_actions: List[Actions]
        :param denied_actions: The denied_actions of this ServerServerIdGroupGroupIdPutRequest.  # noqa: E501
        :type denied_actions: List[Actions]
        """
        self.openapi_types = {
            'name': str,
            'allowed_actions': List[Actions],
            'denied_actions': List[Actions]
        }

        self.attribute_map = {
            'name': 'name',
            'allowed_actions': 'allowed_actions',
            'denied_actions': 'denied_actions'
        }

        self._name = name
        self._allowed_actions = allowed_actions
        self._denied_actions = denied_actions

    @classmethod
    def from_dict(cls, dikt) -> 'ServerServerIdGroupGroupIdPutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _server__server_id__group__group_id__put_request of this ServerServerIdGroupGroupIdPutRequest.  # noqa: E501
        :rtype: ServerServerIdGroupGroupIdPutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ServerServerIdGroupGroupIdPutRequest.


        :return: The name of this ServerServerIdGroupGroupIdPutRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ServerServerIdGroupGroupIdPutRequest.


        :param name: The name of this ServerServerIdGroupGroupIdPutRequest.
        :type name: str
        """

        self._name = name

    @property
    def allowed_actions(self):
        """Gets the allowed_actions of this ServerServerIdGroupGroupIdPutRequest.


        :return: The allowed_actions of this ServerServerIdGroupGroupIdPutRequest.
        :rtype: List[Actions]
        """
        return self._allowed_actions

    @allowed_actions.setter
    def allowed_actions(self, allowed_actions):
        """Sets the allowed_actions of this ServerServerIdGroupGroupIdPutRequest.


        :param allowed_actions: The allowed_actions of this ServerServerIdGroupGroupIdPutRequest.
        :type allowed_actions: List[Actions]
        """

        self._allowed_actions = allowed_actions

    @property
    def denied_actions(self):
        """Gets the denied_actions of this ServerServerIdGroupGroupIdPutRequest.


        :return: The denied_actions of this ServerServerIdGroupGroupIdPutRequest.
        :rtype: List[Actions]
        """
        return self._denied_actions

    @denied_actions.setter
    def denied_actions(self, denied_actions):
        """Sets the denied_actions of this ServerServerIdGroupGroupIdPutRequest.


        :param denied_actions: The denied_actions of this ServerServerIdGroupGroupIdPutRequest.
        :type denied_actions: List[Actions]
        """

        self._denied_actions = denied_actions
