# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mumble_link_server.models.base_model_ import Model
from mumble_link_server import util


class ServerServerIdUserUserIdMovePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, channel_id=None):  # noqa: E501
        """ServerServerIdUserUserIdMovePostRequest - a model defined in OpenAPI

        :param channel_id: The channel_id of this ServerServerIdUserUserIdMovePostRequest.  # noqa: E501
        :type channel_id: int
        """
        self.openapi_types = {
            'channel_id': int
        }

        self.attribute_map = {
            'channel_id': 'channel_id'
        }

        self._channel_id = channel_id

    @classmethod
    def from_dict(cls, dikt) -> 'ServerServerIdUserUserIdMovePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _server__server_id__user__user_id__move_post_request of this ServerServerIdUserUserIdMovePostRequest.  # noqa: E501
        :rtype: ServerServerIdUserUserIdMovePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel_id(self):
        """Gets the channel_id of this ServerServerIdUserUserIdMovePostRequest.


        :return: The channel_id of this ServerServerIdUserUserIdMovePostRequest.
        :rtype: int
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this ServerServerIdUserUserIdMovePostRequest.


        :param channel_id: The channel_id of this ServerServerIdUserUserIdMovePostRequest.
        :type channel_id: int
        """
        if channel_id is None:
            raise ValueError("Invalid value for `channel_id`, must not be `None`")  # noqa: E501

        self._channel_id = channel_id
