# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mumble_link_server.models.base_model_ import Model
from mumble_link_server import util


class ServersCreatePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, max_users=None):  # noqa: E501
        """ServersCreatePostRequest - a model defined in OpenAPI

        :param name: The name of this ServersCreatePostRequest.  # noqa: E501
        :type name: str
        :param max_users: The max_users of this ServersCreatePostRequest.  # noqa: E501
        :type max_users: int
        """
        self.openapi_types = {
            'name': str,
            'max_users': int
        }

        self.attribute_map = {
            'name': 'name',
            'max_users': 'max_users'
        }

        self._name = name
        self._max_users = max_users

    @classmethod
    def from_dict(cls, dikt) -> 'ServersCreatePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _servers_create_post_request of this ServersCreatePostRequest.  # noqa: E501
        :rtype: ServersCreatePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ServersCreatePostRequest.


        :return: The name of this ServersCreatePostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ServersCreatePostRequest.


        :param name: The name of this ServersCreatePostRequest.
        :type name: str
        """

        self._name = name

    @property
    def max_users(self):
        """Gets the max_users of this ServersCreatePostRequest.


        :return: The max_users of this ServersCreatePostRequest.
        :rtype: int
        """
        return self._max_users

    @max_users.setter
    def max_users(self, max_users):
        """Sets the max_users of this ServersCreatePostRequest.


        :param max_users: The max_users of this ServersCreatePostRequest.
        :type max_users: int
        """

        self._max_users = max_users
