# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mumble_link_server.models.base_model_ import Model
from mumble_link_server import util


class ServerServerIdUserUserIdKickPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reason=None):  # noqa: E501
        """ServerServerIdUserUserIdKickPostRequest - a model defined in OpenAPI

        :param reason: The reason of this ServerServerIdUserUserIdKickPostRequest.  # noqa: E501
        :type reason: str
        """
        self.openapi_types = {
            'reason': str
        }

        self.attribute_map = {
            'reason': 'reason'
        }

        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'ServerServerIdUserUserIdKickPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _server__server_id__user__user_id__kick_post_request of this ServerServerIdUserUserIdKickPostRequest.  # noqa: E501
        :rtype: ServerServerIdUserUserIdKickPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self):
        """Gets the reason of this ServerServerIdUserUserIdKickPostRequest.


        :return: The reason of this ServerServerIdUserUserIdKickPostRequest.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ServerServerIdUserUserIdKickPostRequest.


        :param reason: The reason of this ServerServerIdUserUserIdKickPostRequest.
        :type reason: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason
