# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mumble_link_server.models.base_model_ import Model
from mumble_link_server import util


class UserInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, user_name=None, mute=None, deaf=None, self_mute=None, self_deaf=None):  # noqa: E501
        """UserInfo - a model defined in OpenAPI

        :param user_id: The user_id of this UserInfo.  # noqa: E501
        :type user_id: str
        :param user_name: The user_name of this UserInfo.  # noqa: E501
        :type user_name: str
        :param mute: The mute of this UserInfo.  # noqa: E501
        :type mute: bool
        :param deaf: The deaf of this UserInfo.  # noqa: E501
        :type deaf: bool
        :param self_mute: The self_mute of this UserInfo.  # noqa: E501
        :type self_mute: bool
        :param self_deaf: The self_deaf of this UserInfo.  # noqa: E501
        :type self_deaf: bool
        """
        self.openapi_types = {
            'user_id': str,
            'user_name': str,
            'mute': bool,
            'deaf': bool,
            'self_mute': bool,
            'self_deaf': bool
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'user_name': 'user_name',
            'mute': 'mute',
            'deaf': 'deaf',
            'self_mute': 'self_mute',
            'self_deaf': 'self_deaf'
        }

        self._user_id = user_id
        self._user_name = user_name
        self._mute = mute
        self._deaf = deaf
        self._self_mute = self_mute
        self._self_deaf = self_deaf

    @classmethod
    def from_dict(cls, dikt) -> 'UserInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfo of this UserInfo.  # noqa: E501
        :rtype: UserInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this UserInfo.


        :return: The user_id of this UserInfo.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserInfo.


        :param user_id: The user_id of this UserInfo.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def user_name(self):
        """Gets the user_name of this UserInfo.


        :return: The user_name of this UserInfo.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this UserInfo.


        :param user_name: The user_name of this UserInfo.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def mute(self):
        """Gets the mute of this UserInfo.


        :return: The mute of this UserInfo.
        :rtype: bool
        """
        return self._mute

    @mute.setter
    def mute(self, mute):
        """Sets the mute of this UserInfo.


        :param mute: The mute of this UserInfo.
        :type mute: bool
        """

        self._mute = mute

    @property
    def deaf(self):
        """Gets the deaf of this UserInfo.


        :return: The deaf of this UserInfo.
        :rtype: bool
        """
        return self._deaf

    @deaf.setter
    def deaf(self, deaf):
        """Sets the deaf of this UserInfo.


        :param deaf: The deaf of this UserInfo.
        :type deaf: bool
        """

        self._deaf = deaf

    @property
    def self_mute(self):
        """Gets the self_mute of this UserInfo.


        :return: The self_mute of this UserInfo.
        :rtype: bool
        """
        return self._self_mute

    @self_mute.setter
    def self_mute(self, self_mute):
        """Sets the self_mute of this UserInfo.


        :param self_mute: The self_mute of this UserInfo.
        :type self_mute: bool
        """

        self._self_mute = self_mute

    @property
    def self_deaf(self):
        """Gets the self_deaf of this UserInfo.


        :return: The self_deaf of this UserInfo.
        :rtype: bool
        """
        return self._self_deaf

    @self_deaf.setter
    def self_deaf(self, self_deaf):
        """Sets the self_deaf of this UserInfo.


        :param self_deaf: The self_deaf of this UserInfo.
        :type self_deaf: bool
        """

        self._self_deaf = self_deaf
